### ISSUE TITLE
monkey gets too close

### ISSUE THREAD

**Issue by tostonar** [learn-co-curriculum/animal-save#7]
For the monkey to completely avoid the touch of the Spyce Gurls, maybe the max-width should be 1170px instead of 1090px.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
