### ISSUE TITLE
A brief note to clarify that the finished website contains links to individual animal pages

### ISSUE THREAD

**Issue by mdjurdj1** [learn-co-curriculum/animal-save#8]
A few students have noted that they felt confused by the instructions for this lab - specifically, they were not aware that the images on the [finished website](http://learn-co-curriculum.github.io/animal-save/) are actually clickable links to each of the animals you're supposed to "save". Perhaps an additional line of text instructing the students to click the animal images on the home page would clarify this for the few students that don't think to do so.

**Comment by bhollan** [comment]
They look like they work to me.  You have to click on the animal to get to the [Bear page](http://learn-co-curriculum.github.io/animal-save/bear.html), for example.  Then you have to adjust the size of the window/pane to simulate the cliff moving (for the Bear).

**Comment by maxwellbenton** [comment]
Thank you for spotting this and providing feedback.

We have updated the materials and believe the instructions are a bit clearer now.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
